### ISSUE TITLE
coc-html auto tag completion interferes with coc-pairs auto <> completion

### ISSUE THREAD

**Issue by BrianZhang1** [neoclide/coc-html#32]
As the title says, coc-html auto tag completion interferes with coc-pairs auto <> completion.
coc-html autocompletes a tag when it is closed with >, as such:
`<h1>`
_coc-html autocompletes_
`<h1></h1>`

When the > is entered, it auto completes.
The problem is, coc-pairs auto completes < to <>. This means that this would happen:
`<`
_coc-pairs autocompletes_
`<>`
`<h1>`

There is no autocompletion from coc-html since the > was technically never entered. To get the auto completion, you would have to delete the closing > and then add it again, and in that time I could probably just enter the closing \</h1> myself. Is there a work around to this?

**Comment by BrianZhang1** [comment]
Nevermind. This only happens when the code is unindented. I'll close it up.

**Comment by LittleTealeaf** [comment]
Hey, how did you fix this? I've been having this exact issue whether or not the code is indented...

**Comment by chemzqm** [comment]
Can't reproduce, you can disable paired character by filetype like:
```vim
    autocmd FileTyp html let b:coc_pairs_disabled = ['<']
```

**Comment by LittleTealeaf** [comment]
Ok, thanks! I did just try my dotfile configuration on a fresh virtual machine with the same results. If you want to take a look or try it out, my dotfiles repository is public. Otherwise, your solution might have to work for now

(I put it in the `nvim/lua/plugins/_coc.lua` config, incase you want to remove it to see the effects)
